version: '3.8' #Versión del motor de Docker Compose

services:
  # --- BACKEND (NestJS) ---
  api_service:
    build: .
    container_name: nest_api_container
    ports:
      - "3000:3000"
    environment:
      # URL de conexión: postgresql://USUARIO:PASSWORD@HOST:PUERTO/DATABASE
      - DATABASE_URL=postgresql://admin:adminpassword@db_postgres:5432/fiestas_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - NODE_ENV=production
    depends_on:
      db_postgres:
        condition: service_healthy # Espera a que la DB esté realmente lista
    volumes:
      - .:/app
      - /app/node_modules

  # --- BASE DE DATOS (PostgreSQL) ---
  db_postgres:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: fiestas_db
    ports:
      - "5432:5432"
    healthcheck: # Prueba de vida para que la API no intente conectar antes de tiempo
      test: ["CMD-SHELL", "pg_isready -U admin -d fiestas_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

# --- VOLÚMENES PERSISTENTES ---
volumes:
  postgres_data:
